spring:
  application:
    name: springWithRedis
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/cache_management
    username: postgres
    password: Gaurav@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgres
    database-platform: org.hibernate.dialect.PostgresSQLDialect

server:
  port: 8080


